let fname: string = "Nattapat";
let lname: string = "Nuntakure";
let age: number = 19;
let dreamjob: string = "Programmer";
let course: string = "Object Oriented Programming";
let mark1: number = 80;
let mark2: number = 70;
let total: number = mark1 + mark2;
let pass: boolean = true;

console.log("Name %s %s, \nAge: %d, \nDream Job: %s, \nCourse: %s, \nMark: %d",fname, lname, age, dreamjob, course, total);
console.log("Pass: %s", pass);
let courses: string[] = ["Database", "Programming", "Web"];
let marks: number[] = [75,72,81];
console.log(marks);
console.log("\n");
console.log("courses[0]:", marks[0]);
console.log("courses[1]:", marks[1]);
console.log("courses[2]:", marks[2]);
console.log("\n");
total = marks[0] + marks[1] + marks[2];
let average = total / marks.length;
console.log("Total", total);
console.log("Average", average);